projeto_fazenda/accounts/urls.py
from django.urls import path

from . import views

# Lista responsável por registrar os caminhos do nosso site
urlpatterns = [
    path('register/', views.SignUp.as_view(), name='signup')
]

projeto_fazenda/projeto_fazenda/urls.py
from django.contrib import admin
from app_fazenda import views
from django.urls import path, include



# Lista responsável por registrar os caminhos do nosso site
urlpatterns = [
    # Rota, view responsável, nome de referência
    path('', views.home, name='home' ),

    # Caminhos parte cadastro
    path('admin/', admin.site.urls),
    path('cadastrar_dados/', views.cadastro, name='cadastro_dados'),
    path('listagem_dados/', views.listagem, name='listagem_dados'),
    path('excluir_dados/<int:pk>/', views.DadosDeleteView.as_view(), name='excluir_dados'),
    path('editar_dados/<int:pk>/', views.DadosUpdateView.as_view(), name='editar_dados'),

    # Caminhos parte detalhes dos dados 
    path('selecionar_cultivo/', views.selecionar, name='selecionar'),
    path('selecionar/detalhes_do_cultivo/', views.detalhe, name='detalhe'),
    
    # Caminhos cadastrar cultivo
    path('cadastrar_cultivo/', views.cadastrar_cultivo, name='cadastrar_cultivo'),
    path('listagem_cultivos/', views.listar_cultivos, name='listar_cultivos'),
    path('editar_cultivo/<int:pk>/', views.CultivoUpdateView.as_view(), name='editar_cultivo'),
    path('excluir_cultivo/<int:pk>/', views.CultivoDeleteView.as_view(), name='excluir_cultivo'),

    # Registro usuário
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

projeto_fazenda/accounts/models.py
from django.db import models

# Create your models here.

projeto_fazenda/app_fazenda/models.py
from django.db import models
from django.contrib.auth import get_user_model



# Criação do banco de dados para registrar os dados
class Dados(models.Model):
    id = models.AutoField(primary_key=True)
    bloco = models.IntegerField()
    cultivo = models.TextField(max_length=255)
    ph = models.FloatField()
    umidade = models.FloatField()
    textura = models.TextField(max_length=255)
    data = models.DateField(auto_now_add=True)
    # Se um usuário for apagado, apagar todos os dados do usuário também
    usuario = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)



# Criação do banco de dados para tipos de cultivos
class Cultivo(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=255)
    umidade_recomendado = models.FloatField()
    ph_recomendado = models.FloatField()
    texto_recomendacao = models.TextField(max_length=1200, null=True)
    # Se um usuário for apagado, apagar todos os dados do usuário também
    usuario = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

projeto_fazenda/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/register.html'
    

projeto_fazenda/app_fazenda/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView, UpdateView
from .models import Dados, Cultivo
from .form import DadosForm, CultivoForm, UpdateDadosForm
from django.contrib.auth.decorators import login_required


# Classe genérica do django para view de delete nos Dados

class DadosDeleteView(DeleteView):
    model = Dados
    template_name = 'dados/excluir.html'
    success_url = reverse_lazy('listagem_dados')



# Classe genérica do django para view de update nos Dados
class DadosUpdateView(UpdateView):
    model = Dados
    form_class = UpdateDadosForm
    template_name = 'dados/editar.html'
    success_url = reverse_lazy('listagem_dados')



# Classe genérica do django para view de delete nos Cultivos
class CultivoDeleteView(DeleteView):
    model = Cultivo
    template_name = 'cultivo/excluir.html'
    success_url = reverse_lazy('listar_cultivos')



# Classe genérica do django para view de update nos Cultivos
class CultivoUpdateView(UpdateView):
    model = Cultivo
    form_class = CultivoForm
    template_name = 'dados/editar.html'
    success_url = reverse_lazy('listar_cultivos')



# View cadastro dos dados
@login_required
def cadastro(request):
    print(request.POST)
    # Se a requisição da página for POST
    if request.method == 'POST':
        
        form = DadosForm(request.POST, user=request.user)
        # Formulário válido:
        if form.is_valid():
            form.save()
            return redirect('listagem_dados')
        # Formulário não é válido:
        else:
            print(form.errors)
            return render(request, 'dados/cadastro.html', {'form': form})
    # Se a requisição da página for GET
    else:
        form = DadosForm(user=request.user)
    return render(request, 'dados/cadastro.html', {'form': form})



# View listagem dos dados
@login_required
def listagem(request):
    # Se a requisição da página for POST
    if request.method == 'POST':
        form = DadosForm(request.POST)
        # Formulário válido:
        if form.is_valid():
            dados_instance = form.save(commit=False)  # Não salva ainda
            dados_instance.usuario = request.user  # Define o usuário
            dados_instance.save()  # Agora salva
            return redirect('listagem_dados')
        # Formulário não é válido:
        else:
            print(form.errors)  # Verificar quais erros estão presentes
            return render(request, 'dados/cadastro.html', {'form': form})

    # Se a requisição da página for GET
    else:
        form = DadosForm()
    
    # Coloca os dados recebidos em um dicionário
    dados = {
        'dados': Dados.objects.filter(usuario=request.user),  # Filtra pelos dados do usuário
        'form': form
    }

    # Retorna a página listagem, com os dados inseridos com sucesso no banco
    return render(request, 'dados/listagem.html', dados)


# View para a tela de seleção do cultivo para detalhes
@login_required
def selecionar(request):
    cultivos = Cultivo.objects.filter(usuario=request.user)
    return render(request, 'detalhe_cultivo/selecionar.html', {'cultivos': cultivos})


# View para tela de detalhes do cultivo
@login_required
def detalhe(request):
    if request.method == 'POST':
        cultivo_nome = request.POST.get('cultivo')
        
        # Filtra os cultivos pelo nome e pelo usuário logado
        cultivos = Cultivo.objects.filter(nome=cultivo_nome, usuario=request.user)

        dados_filtrados = Dados.objects.filter(cultivo=cultivo_nome, usuario=request.user)

    # Obtém o último registro
        try:
            ultimo_registro = dados_filtrados.latest('id')
        except Dados.DoesNotExist:
            ultimo_registro = None
        

        # Coloca os dados do contexto em um dict para renderizar as páginas com as informações do dict
        dados = {
            'cultivos': cultivos,
            'ultimo_registro': ultimo_registro
        }

        # Renderiza a página com os dados dos cultivos
        return render(request, 'detalhe_cultivo/detalhe.html', dados)

    # Caso não houver POST
    else:
        return render(request, 'detalhe_cultivo/detalhe.html')
    
# Home
@login_required
def home(request):
    return render(request, 'inicio/home.html')


# View para cadastrar cultivos
@login_required
def cadastrar_cultivo(request):
    # Se a requisição da página for POST
    if request.method == 'POST':
        form = CultivoForm(request.POST)
         # Formulário válido:
        if form.is_valid():
            cultivo_instance = form.save(commit=False)  # Não salva ainda
            cultivo_instance.usuario = request.user  # Define o usuário antes de salvar
            cultivo_instance.save()  # Agora salva
            return redirect('listar_cultivos')
        # Fomulário não válido:
        else: 
            redirect('cadastrar_cultivo/')
    else:
        form = CultivoForm()
    return render(request, 'cultivo/cadastrar.html', {'form': form})


# View para listar os cultivos
@login_required
def listar_cultivos(request):
    # Obtém todos os cultivos cadastrados para o usuário logado
    cultivos = Cultivo.objects.filter(usuario=request.user)  # Filtra pelos cultivos do usuário
    # Cria um dicionário com os cultivos para passar ao template
    dados = {
        'dados': cultivos
    }
    # Retorna a página de listagem, com os cultivos do banco de dados
    return render(request, 'cultivo/listar_cultivos.html', dados)

projeto_fazenda/app_fazenda/templates/base.html
<!doctype html>
<html lang="pt-BR">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Meu Sistema{% endblock %}</title>
        {% load static %}

        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css">
    </head>
    <body>
    <!-- Cabeçalho -->
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-success">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">Solo-Smart</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Cadastros
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'cadastrar_cultivo' %}">Cadastrar cultivo</a></li>
                                    <li><a class="dropdown-item" href="{% url 'cadastro_dados' %}">Cadastrar dados</a></li>
                                </ul>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Listagem
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'listar_cultivos' %}">Listar cultivos</a></li>
                                    <li><a class="dropdown-item" href="{% url 'listagem_dados' %}">Listar dados</a></li>
                                </ul>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'selecionar' %}">Detalhes</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="/accounts/login">Entrar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/accounts/register">Cadastrar-se</a>
                            </li>
                        {% endif %}
                    </ul>
                    <form action="{% url 'logout' %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-light">Sair</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    <!-- Conteúdo principal -->
    <div class="container mt-4">
        {% block content %}
        <!-- O conteúdo de cada pagina sera inserido aqui -->
        {% endblock %}
    </div>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 bg-success text-white">
        <div class="container text-center">
            <span>&copy; 2024 Solo-Smart - Todos os direitos reservados</span>
        </div>
    </footer>

        <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

projeto_fazenda/app_fazenda/templates/cadastro/cadastro.html
{% extends 'base.html' %} <!-- Trazendo o arquivo base -->


{% block title %}Cadastrar{% endblock %}
{% block content %}

<form method="POST" action="{% url 'dados_fazenda' %}">
    {% csrf_token %}
    <p>{{ form.non_field_errors }}</p>  <!-- Erros gerais -->

    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label">Bloco: </label>
        <div class="col-sm-10">
            {{ form.bloco }}
            <p>{{ form.bloco.errors }}</p>  <!-- Erros específicos do campo -->
        </div>
    </div>

    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label">Cultivo: </label>
        <div class="col-sm-10">
            {{ form.cultivo }}
            <p>{{ form.cultivo.errors }}</p>
        </div>
    </div>

    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label">PH: </label>
        <div class="col-sm-10">
            {{ form.ph }}
            <p>{{ form.ph.errors }}</p>
        </div>
    </div>

    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label">Umidade: </label>
        <div class="col-sm-10">
            {{ form.umidade }}
            <p>{{ form.umidade.errors }}</p>
        </div>
    </div>

    <div class="mb-3 row">
        <label class="col-sm-2 col-form-label">Textura: </label>
        <div class="col-sm-10">
            {{ form.textura }}
            <p>{{ form.textura.errors }}</p>
        </div>
    </div>

    <div> 
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
    </form>

{% endblock %}

projeto_fazenda/app_fazenda/templates/cadastro/confirmar_exclusao.html
{% extends 'base.html' %}

{% block title %}Confirmar exclusão{% endblock %}
{% block content %}

  <h2>Tem certeza de que deseja excluir este dado?</h2>
  <p>Bloco: {{ object.bloco }}</p>
  <p>cultivo: {{ object.cultivo }}</p>
  <p>PH: {{ object.ph }}</p>
  <p>Textura: {{ object.textura }}</p>

  <form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Excluir</button>
    <a href="{% url 'dados_fazenda' %}" class="btn btn-secondary">Cancelar</a>
  </form>

{% endblock %}

projeto_fazenda/app_fazenda/templates/cadastro/editar_dados.html
{% extends 'base.html' %}
{% block title %}Editar dados{% endblock %}
{% block content %}

<!-- Traz o formulário para edição -->
<h1>Editar Dados</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Salvar alterações</button>
</form>

{% endblock %}

projeto_fazenda/app_fazenda/templates/cultivo/cadastrar.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Cadastrar Cultivo{% endblock %}

{% block content %}
<div class="container mt-5 p-4 bg-light border rounded shadow" style="margin-bottom: 50px;">
    <h1 class="mb-4">Cadastre o cultivo</h1>
    <form method="POST" action="{% url 'cadastrar_cultivo' %}">
        {% csrf_token %}
        <p>{{ form.non_field_errors }}</p>

        <div class="form-group">
            <label for="id_nome">Nome do Cultivo</label>
            {{ form.nome }}
            <div class="text-danger">{{ form.nome.errors }}</div> 
        </div>

        <div class="form-group">
            <label for="id_umidade_recomendado">Umidade Recomendada (%)</label>
            {{ form.umidade_recomendado }}
            <div class="text-danger">{{ form.umidade_recomendado.errors }}</div> 

        <div class="form-group">
            <label for="id_ph_recomendado">pH Recomendado</label>
            {{ form.ph_recomendado }}
            <div class="text-danger">{{ form.ph_recomendado.errors }}</div>
        </div>

        <div class="form-group">
            <label for="id_texto_recomendacao">Recomendações</label>
            {{ form.texto_recomendacao }} 
            <div class="text-danger">{{ form.texto_recomendacao.errors }}</div> 
        </div>

        <div class="mt-3">
            <button type="submit" class="btn btn-primary">Enviar</button>
        </div>
    </form>
</div>
{% endblock %}

projeto_fazenda/app_fazenda/templates/cultivo/editar.html
{% extends 'base.html' %}
{% block title %}Editar dados{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Editar Dados</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center">
                    Preencha os campos abaixo
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}

                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-primary btn-lg">Salvar alterações</button>
                            <a href="{% url 'listar_cultivos' %}" class="btn btn-secondary btn-lg">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

projeto_fazenda/app_fazenda/templates/cultivo/excluir.html
{% extends 'base.html' %}

{% block title %}Confirmar Exclusão{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Tem certeza que deseja excluir este dado?</h4>
        <hr>
        <p><strong>Nome:</strong> {{ object.nome }}</p>
        <p><strong>Umidade recomendada:</strong> {{ object.umidade_recomendado }}</p>
        <p><strong>pH recomendado:</strong> {{ object.ph_recomendado }}</p>
        <p><strong>Texto de recomendação:</strong> {{ object.texto_recomendacao }}</p>
    </div>

    <form method="POST" class="mt-3">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger me-2">Excluir</button>
        <a href="{% url 'listar_cultivos' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

projeto_fazenda/app_fazenda/templates/cultivo/listar_cultivos.html
{% extends 'base.html' %}

{% block title %}Listagem de cultivos{% endblock %}

{% block content %}

<div class="container mt-5">
    <a style="margin: 0;" href="{% url 'cadastrar_cultivo' %} " class="btn btn-success">Voltar ao cadastro</a>
    <h1 class="mb-4 text-center">Listagem dos Cultivos</h1>
    <hr>
    <div id="div-cultivo" class="table-responsive">
        <table class="table table-bordered table-striped text-center align-middle" id="tabela-cultivos">
            <thead class="bg-success text-white">
                <tr>
                    <th>Nome</th>
                    <th>Umidade Recomendada</th>
                    <th>pH Recomendado</th>
                    <th>Texto de Recomendação</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for dado in dados %}
                <tr>
                    <td>{{ dado.nome }}</td>
                    <td>{{ dado.umidade_recomendado }}</td>
                    <td>{{ dado.ph_recomendado }}</td>
                    <td>{{ dado.texto_recomendacao }}</td>
                    <td>
                        <div class="d-flex justify-content-center">
                            <a href="{% url 'editar_cultivo' dado.pk %}" class="btn btn-warning mx-1">Editar</a>
                            <a href="{% url 'excluir_cultivo' dado.pk %}" class="btn btn-danger mx-1">Excluir</a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

projeto_fazenda/app_fazenda/templates/dados/cadastro.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Cadastrar dados{% endblock %}

{% block content %}

<div class="container mt-5 p-4 bg-light border rounded shadow" style="margin-bottom: 50px;">
    <h1 class="mb-4">Registre os dados</h1>
    <form method="POST" action="{% url 'listagem_dados' %}">
        {% csrf_token %}
        {{ form|crispy }}
        
        <div class="mt-3">
            <button type="submit" class="btn btn-success">Enviar</button>
        </div>
    </form>
</div>

{% endblock %}

projeto_fazenda/app_fazenda/templates/dados/editar.html
{% extends 'base.html' %}
{% block title %}Editar dados{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Editar Dados</h1>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">
                    Preencha os campos abaixo
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }} 

                        <div class="text-center mt-4">
                            <button type="submit" class="btn btn-primary btn-lg">Salvar alterações</button>
                            <a href="{% url 'listagem_dados' %}" class="btn btn-secondary btn-lg">Cancelar</a>
                        </div>

                        <div class="text-center mt-4">
                            
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

projeto_fazenda/app_fazenda/templates/dados/excluir.html
{% extends 'base.html' %}

{% block title %}Confirmar exclusão{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Tem certeza que deseja excluir este dado?</h4>
        <hr>
        <p><strong>Bloco:</strong> {{ object.bloco }}</p>
        <p><strong>Cultivo:</strong> {{ object.cultivo }}</p>
        <p><strong>pH:</strong> {{ object.ph }}</p>
        <p><strong>Textura:</strong> {{ object.textura }}</p>
    </div>

    <form method="POST" class="mt-3">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger me-2">Excluir</button>
        <a href="{% url 'listagem_dados' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

projeto_fazenda/app_fazenda/templates/dados/listagem.html
{% extends 'base.html' %}

{% block title %}Listagem dos Dados{% endblock %}

{% block content %}
<div class="container mt-5">
    <a style="margin: 0;" href="{% url 'cadastro_dados' %} " class="btn btn-success">Voltar ao cadastro</a>
    <h1 class="mb-4 text-center">Listagem dos Dados</h1>
    <hr>
    <div id="div-lista" class="table-responsive">
        <table class="table table-bordered table-striped text-center align-middle" id="lista-dados">
            <thead class="bg-success text-white">
                <tr>
                    <th>Bloco</th>
                    <th>Cultivo</th>
                    <th>PH</th>
                    <th>Umidade</th>
                    <th>Textura</th>
                    <th>Data de Inclusão</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                <!-- Iteração dentro do banco de dados -->
                {% for dado in dados %}
                <tr>    
                    <td>{{ dado.bloco }}</td>
                    <td>{{ dado.cultivo }}</td>
                    <td>{{ dado.ph }}</td>
                    <td>{{ dado.umidade }}</td>
                    <td>{{ dado.textura }}</td>  
                    <td>{{ dado.data }}</td>
                    <td>
                        <div class="d-flex justify-content-center">
                            <a href="{% url 'editar_dados' dado.pk %}" class="btn btn-warning mx-1">Editar</a>
                            <a href="{% url 'excluir_dados' dado.pk %}" class="btn btn-danger mx-1">Excluir</a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

projeto_fazenda/app_fazenda/templates/detalhe_cultivo/detalhe.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Detalhes do Cultivo{% endblock %}

{% block content %}
<div class="container mt-5">
    {% if cultivos %}
        <div class="row justify-content-center">
            {% for cultivo in cultivos %}
            <div class="col-md-8 mb-4">
                <div class="card">
                    <div class="card-header bg-success text-white">
                        <h4 class="text-center">{{ cultivo.nome }}</h4>
                    </div>
                    <div class="card-body">
                        <h5>Recomendações do Cultivo</h5>
                        <p><strong>Umidade recomendada:</strong> {{ cultivo.umidade_recomendado }}%</p>
                        <p><strong>pH recomendado:</strong> {{ cultivo.ph_recomendado }}</p>
                        <p>{{ cultivo.texto_recomendacao }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-warning text-center" role="alert">
            Nenhum cultivo encontrado ou selecionado.
        </div>
    {% endif %}
</div>

<div class="container mt-5">
    <h2 class="text-center mb-4">Último Registro</h2>
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead class="table-dark">
                <tr>
                    <th>Bloco</th>
                    <th>Cultivo</th>
                    <th>pH</th>
                    <th>Umidade</th>
                    <th>Textura</th>
                    <th>Data da Inclusão</th>
                </tr>
            </thead>
            <tbody>
                <!-- Verifica se tem algum último registro -->
                {% if ultimo_registro %}
                    <!-- Caso tenha, ele exibe -->
                    <tr>
                        <td>{{ ultimo_registro.bloco }}</td>
                        <td>{{ ultimo_registro.cultivo }}</td>
                        <td>{{ ultimo_registro.ph }}</td>
                        <td>{{ ultimo_registro.umidade }}</td>
                        <td>{{ ultimo_registro.textura }}</td>
                        <td>{{ ultimo_registro.data }}</td>
                    </tr>
                {% else %}
                    <!-- Caso não tenha -->
                    <tr>
                        <td colspan="6" class="text-center">Nenhum registro encontrado ou selecionado.</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

projeto_fazenda/app_fazenda/templates/detalhe_cultivo/selecionar.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Selecionar Cultivo{% endblock %}

{% block content %}
<div class="div-cadastro">
    <h1>Selecione um Cultivo</h1>
    <form method="post" action="{% url 'detalhe' %}" class="row g-3">
        {% csrf_token %}
        <select name="cultivo" id="cultivo" class="form-select">
            {% for cultivo in cultivos %}
                <option value="{{ cultivo.nome }}">{{ cultivo.nome }}</option>
            {% endfor %}
        </select>
        <button type="submit" class="btn btn-success">Buscar</button>
    </form>
</div>
{% endblock %}

projeto_fazenda/app_fazenda/templates/inicio/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container mt-5" style="margin-bottom: 50px;">
    <h1 class="text-center mb-4">Bem-vindo ao Solo-Smart</h1>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card text-center">
                <div class="card-header">
                    O que você gostaria de fazer?
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <a href="{% url 'cadastro_dados' %} " class="btn btn-success btn-lg">Cadastrar dados</a>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'listagem_dados' %}" class="btn btn-success btn-lg">Listagem de dados</a>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'cadastrar_cultivo' %}" class="btn btn-success btn-lg">Cadastrar cultivos</a>
                    </div>
                    <div class="mb-3">
                        <a href="{% url 'listar_cultivos' %}" class="btn btn-success btn-lg">Listagem de cultivos</a>
                    </div>
                </div>
                <div class="card-footer text-muted">
                    Use as opções acima para gerenciar seus dados.
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}